[config]
port = 7000

[[data]]
method = "GET"
path = "/"
result_type = "file"
result = "C:\\Workstation\\Programming\\Rust\\fake-rest\\examples\\result.json"
status_code = 200
result_headers = [ #optional: these headers gonna return on response
    "Content-Length : 1024", 
    "Accept : application/json"
]
headers = [ #optional: request must have these headers
    "Authorization",
    "Content-Length"
]
queries = [ #optional: request must have these queries
    "hello", # key "hello" = value "whatever"
    "fine",
]

[[data]]
method = "GET"
path = "/hello"
result_type = "direct"
result = ""
status_code = 200
result_headers = [
    "Content-Length : 1024", 
    "Accept : application/json"
]
