[config]
# for expose a port on the server: "0.0.0.0" 
# for run on localhost on your machine: "127.0.0.1"
host = "127.0.0.1"
port = 7000

# full example
[[data]]
method = "GET"
path = "/"
result_type = "file"
result = "examples/result.json" # It's for the sake of an example. better to use the full path.
status_code = 200
result_headers = [ #optional: these headers gonna return on response
    "Content-Type : application/json"
]
headers = [ #optional: request must have these headers
     "Authorization", # Just check if header exists on request
     "SomeHeader: SomeValue", # Check the existance of header and compare value
]
queries = [ #optional: request must have these queries
    # "hello",
    # "test"
]

# simple example(required fields)
[[data]]
method = "GET"
path = "/hello"
result_type = "direct"
result = ""
status_code = 200

# serve a file for download
[[data]]
method = "GET"
path = "/dl"
result_type = "dl"
# unix:    "examples/download.txt"
# windows: ".\\examples\\download.txt"
result = "examples/download.txt"