[config]
port = 7000

[[data]]
method = "GET"
path = "/"
result_type = "file"
result = "C:\\Workstation\\Programming\\Rust\\fake-rest\\examples\\result.json"
status_code = 200
headers = [#optional
    "Content-Length : 1024", 
    "Accept : application/plain"
]
queries = [#optional
    "hello = how are you",
    "fine = thank you",
]

[[data]]
method = "GET"
path = "/hello"
result_type = "direct"
result = "{\"meg\" : \"hello!\"}"
status_code = 200
headers = [
    "Content-Length : 1024", 
    "Accept : application/json"
]
